### ISSUE TITLE
[🚀 FEAT] CI/CD pipeline 구축

### ISSUE THREAD

**Issue by rlaekdud** [rlaekdud/lingo-be#13]
**🛠️ Functional requirements**
- 배포 서버에 CI/CD pipeline을 구축해 DevOps 적용

**✔️ TODO**
- [x] 배포 서버 보안 설정(포트 열기)
- [x] 배포 서버에 할당 받은 계정을 sudoers로 등록(배포 시 필요)
- [x] Github secrete variable 설정
- [x] local 환경에 배포하기 위한 workflow 파일 작성
- [x] Github actions workflow 적용(commit)

**🖍️ Describe alternatives**
- 배포 후 테스트 적용 필요
