### ISSUE TITLE
[🚀 FEAT] AI 서버 배포 API 연결 대응 및 테스트

### ISSUE THREAD

**Issue by rlaekdud** [rlaekdud/lingo-be#16]
**🛠️ Functional requirements**
- AI 서버 배포 진행 후 AI와 연결해 사용하는 API(translation, suggestion) 테스트 

**✔️ TODO**
- [x] AI 서버 배포 관련 이슈 대응(CI/CD pipeline 구축)
- [x] `/model-list` api 수정(response 형식 변경)
- [x] test(6/25 예정)
  - [x] translation api response object mapping 정상 동작 확인(HashMap → dictionary)
  - [x] suggestion api response object mapping 정상 동작 확인(dictionary → HashMap)
- [x] object mapping이 제대로 되지 않을 시 debugging

**🖍️ Describe alternatives**
- AI 서버 배포 관련 이슈 대응 필요

**Comment by rlaekdud** [comment]
**배포 서버 이슈로 인해 일정 지연**
- 서버실 에어컨 고장으로 서버가 꺼진 것으로 추정
- ~~복구 시점 미정~~

**6월 25일 14:46 서버 해결 완료**
- 서버 재부팅으로 해결

**Comment by rlaekdud** [comment]
**AI 서버에 api 요청 시 오류 발생**
- request : 
`{"model":"llama2_7b","targetWord":"CT","sentence":false,"cntxt_len":0,"text":"","abbreviation":true}`
- response : 
`422 Unprocessable Entity: "{"detail":[{"type":"missing","loc":["body"],"msg":"Field required","input":null}]}"`
---
[비슷한 사례](https://wikidocs.net/176427)를 찾았으나, 정확한 원인 불명
- postman에서 동일한 json으로 request를 보낸 경우 정상 동작

---
python의 json 라이브러리에서 파라미터로 문자열이 아닌 `requestJSON` 객체를 사용하기 때문인 것으로 추정
- 자세한 사항은 [여기](https://pavolkutaj.medium.com/how-to-fix-422-client-error-unprocessable-entity-when-using-json-parameter-of-request-python-8650af63bf56) 참고

**Comment by rlaekdud** [comment]
**AI 서버로부터 응답을 가져올 때 오류가 나는 문제 해결**
- FastAPI의 경우 타겟 url에 `http://`를 붙여야 함 → 붙여서 해결
- `GET` 요청을 `POST` 요청으로 바꿔 형식에 맞게 변경
