### ISSUE TITLE
[🚀 FEAT] modify suggestion api service logic

### ISSUE THREAD

**Issue by rlaekdud** [rlaekdud/lingo-be#18]
**🛠️ Functional requirements**
- A communication error occurred during the design of the suggestion api.
- add new logic in suggestion api
  - use suggestion api(AI server), that provide eng word suggestion
  - source lan word → translate to english → suggestion → translate to source lan → remove duplicated word

**✔️ TODO**
- [x] modify api specification
- [x] add translation logic(source lan to english)
- [x] add deletion logic of duplicated suggestion result

**🖍️ Describe alternatives**
- death line : 2024/07/08
