### ISSUE TITLE
[🚀 FEAT] model-list api 기능 요구사항

### ISSUE THREAD

**Issue by rlaekdud** [rlaekdud/lingo-be#6]
**🛠️ Functional requirements**
- AI에서 모델 추가/삭제 시 이를 프론트엔드에 반영하기 위해 AI 웹 서버로부터 모델 리스트를 가져오는 api
- FE에서 모델 리스트 요청을 받을 시 AI로부터 모델 리스트를 가져오고 FE로 전송

**✔️ TODO**
- [x] `/model-list` api 설계 및 정의
- [x] model-list controller impl
- [x] model-list service impl

**🖍️ Describe alternatives**
- none

**Comment by rlaekdud** [comment]
`/model-list` api 설계 및 정의 완료.
해당 api spec을  [confluence](https://ipalab.atlassian.net/wiki/spaces/Lingo/pages/47415329/Lingo+API+specification#Translation.1)에 업로드 완료.
