### ISSUE TITLE
[🚀 FEAT] api 수정 대응 메뉴얼 작성

### ISSUE THREAD

**Issue by rlaekdud** [rlaekdud/lingo-be#7]
**🛠️ Functional requirements**
- 차후 api를 수정하게 될 것을 대비해 이에 대응하는 메뉴얼 작성 필요

**✔️ TODO**
- [x] api 수정 시 수정해야 할 항목 정리
    - [x] api request/response, flask request/response
    - [x] service logic
    - [x] controller
- [x] 각 항목 별로 수정해야 하는 사항 및 주의사항 정리
- [x] 전체 코드 `javadoc` 작성을 통한 가독성 확보

**🖍️ Describe alternatives**
- 인계 시 문제 없도록 작성할 것
