### ISSUE TITLE
[🚀 FEAT] AI translation api request/response format 수정 사항 반영 

### ISSUE THREAD

**Issue by rlaekdud** [rlaekdud/lingo-be#8]
**🛠️ Functional requirements**
- AI translation api를 더 직관적으로 수정함에 따른 BE dto 변경

**✔️ TODO**
- [x] request body(kargs → kwargs) dto 수정
- [x] response body(query → output ) dto 수정
- [x] 각 dto 수정에 따른 service logic 수정 

**🖍️ Describe alternatives**
- none
